version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    commit-message:
      prefix: gomod
    labels:
      - dependencies
      - go

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    commit-message:
      prefix: actions
    labels:
      - dependencies
      - github-actions
