# This file was generated by scripts/publish-tap.sh. DO NOT EDIT.
cask "xray" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "b9c32bd500e59e35f8e94b5f0cd5a8330b263d47c22fedd04cf512b1a478db7b"
      url "https://github.com/kmcd/xray/releases/download/v#{version}/xray_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "459449e20318186a75837d5473bee83ead0fa618504064d5f951eff36114f526"
      url "https://github.com/kmcd/xray/releases/download/v#{version}/xray_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e1ffe5713136d534afdcb748d9c63ff34fe58408ebd56a38e9d5a204dc7e13e4"
      url "https://github.com/kmcd/xray/releases/download/v#{version}/xray_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3f3cdaed9f6adc2d20545528f250e4c7bf0a7723280f8816e2f018266641fb04"
      url "https://github.com/kmcd/xray/releases/download/v#{version}/xray_#{version}_linux_arm64.tar.gz"
    end
  end

  name "xray"
  desc "Read-only extractor for engineering metrics — git, GitHub, CI, observability — into a portable .tar.gz"
  homepage "https://github.com/kmcd/xray"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "xray"

  # Strip macOS Gatekeeper's quarantine xattr so the cosign-signed (but not
  # Apple-notarized) binary runs without the "Apple could not verify..."
  # dialog. The binary's provenance is verified by Sigstore + SLSA L3, not
  # Apple notarization; this postflight tells macOS to skip its own check.
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{staged_path}/xray"],
                   sudo: false
  end
end
