# This file was generated by scripts/publish-tap.sh. DO NOT EDIT.
cask "xray" do
  version "0.4.1"

  on_macos do
    on_intel do
      sha256 "ca0350561dc115cef7b26838d9f13c495e8ab598dec9ad50efe253c49bedfdc3"
      url "https://github.com/kmcd/xray/releases/download/v#{version}/xray_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "edf21db78a745a2996df40ce9e085f5e82814001d93ba8abf1177b95e1675edf"
      url "https://github.com/kmcd/xray/releases/download/v#{version}/xray_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "262ad6cb9478199386cd22fce79c66913593960ef985dd69c1033540736f361e"
      url "https://github.com/kmcd/xray/releases/download/v#{version}/xray_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "71af42b02baa26f25b53fdfd4344e3dd4b27146f3be4a45146d9cb9903e734bb"
      url "https://github.com/kmcd/xray/releases/download/v#{version}/xray_#{version}_linux_arm64.tar.gz"
    end
  end

  name "xray"
  desc "Read-only extractor for engineering metrics — git, GitHub, CI, observability — into a portable .tar.gz"
  homepage "https://github.com/kmcd/xray"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "xray"

  # Strip macOS Gatekeeper's quarantine xattr so the cosign-signed (but not
  # Apple-notarized) binary runs without the "Apple could not verify..."
  # dialog. The binary's provenance is verified by Sigstore + SLSA L3, not
  # Apple notarization; this postflight tells macOS to skip its own check.
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{staged_path}/xray"],
                   sudo: false
  end
end
