# This file was generated by scripts/publish-tap.sh. DO NOT EDIT.
cask "xray" do
  version "0.4.2"

  on_macos do
    on_intel do
      sha256 "875f3540fde8a2885144de119d78dec9742371fa0526fbd191628b250776cac6"
      url "https://github.com/kmcd/xray/releases/download/v#{version}/xray_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0afcd034467162e509e1d12a9401b55edd5617375e22b835f7bd12faecdd6412"
      url "https://github.com/kmcd/xray/releases/download/v#{version}/xray_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f008f22c6e3b0e79935fe645d68bbc7edae5597c0a7cab6ea88083032d4e0fe6"
      url "https://github.com/kmcd/xray/releases/download/v#{version}/xray_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "acd14725c2c2830146ce4f1d9c5160f86e91c95e55b9f3e7efba3981f597a619"
      url "https://github.com/kmcd/xray/releases/download/v#{version}/xray_#{version}_linux_arm64.tar.gz"
    end
  end

  name "xray"
  desc "Read-only extractor for engineering metrics — git, GitHub, CI, observability — into a portable .tar.gz"
  homepage "https://github.com/kmcd/xray"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "xray"

  # Strip macOS Gatekeeper's quarantine xattr so the cosign-signed (but not
  # Apple-notarized) binary runs without the "Apple could not verify..."
  # dialog. The binary's provenance is verified by Sigstore + SLSA L3, not
  # Apple notarization; this postflight tells macOS to skip its own check.
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{staged_path}/xray"],
                   sudo: false
  end
end
