# This file was generated by scripts/publish-tap.sh. DO NOT EDIT.
class Xray < Formula
  desc "Read-only extractor for engineering metrics — git, GitHub, CI, observability — into a portable .tar.gz"
  homepage "https://github.com/kmcd/xray"
  version "0.4.12"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/kmcd/xray/releases/download/v#{version}/xray_#{version}_darwin_amd64.tar.gz"
      sha256 "76400a18d9d3100cc643b03324b461d24a534dadf4d7c4e6ba4bbc2fdbb6dd16"
    end
    on_arm do
      url "https://github.com/kmcd/xray/releases/download/v#{version}/xray_#{version}_darwin_arm64.tar.gz"
      sha256 "9b6010caff74ede03e2ab66dadc5fdc5958d7a09968d34e85b3944343aa4e729"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kmcd/xray/releases/download/v#{version}/xray_#{version}_linux_amd64.tar.gz"
      sha256 "5ebf2f89ed8f375ea3e33067b24ea1ce5dce910183ee9041754c80442f2b94fc"
    end
    on_arm do
      url "https://github.com/kmcd/xray/releases/download/v#{version}/xray_#{version}_linux_arm64.tar.gz"
      sha256 "39f24375744b52d10e799bd37946d22f3c416466f623529ee4f2a2259512a85b"
    end
  end

  livecheck do
    skip "Auto-generated on release."
  end

  def install
    bin.install "xray"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/xray version")
  end
end
