# This file was generated by scripts/publish-tap.sh. DO NOT EDIT.
class Xray < Formula
  desc "Read-only extractor for engineering metrics — git, GitHub, CI, observability — into a portable .tar.gz"
  homepage "https://github.com/kmcd/xray"
  version "0.4.6"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/kmcd/xray/releases/download/v#{version}/xray_#{version}_darwin_amd64.tar.gz"
      sha256 "3102fb71211278d52c26fdc16e631f711762bfeef3c3921089bbc964f676c2d0"
    end
    on_arm do
      url "https://github.com/kmcd/xray/releases/download/v#{version}/xray_#{version}_darwin_arm64.tar.gz"
      sha256 "90158b3d6eadfe33b3fc6ef5d35057a2c96f352b8612443444c34d6750f91dce"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kmcd/xray/releases/download/v#{version}/xray_#{version}_linux_amd64.tar.gz"
      sha256 "6e7461eb8c1990d520984a52c3c8e360cb89518783fc11a990384bfe18d19e62"
    end
    on_arm do
      url "https://github.com/kmcd/xray/releases/download/v#{version}/xray_#{version}_linux_arm64.tar.gz"
      sha256 "9681ea7c35c86c4d92bfead5f441b78015f7b678eafb4e514fe586dc50a20ea7"
    end
  end

  livecheck do
    skip "Auto-generated on release."
  end

  def install
    bin.install "xray"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/xray version")
  end
end
