# This file was generated by scripts/publish-tap.sh. DO NOT EDIT.
class Xray < Formula
  desc "Read-only extractor for engineering metrics — git, GitHub, CI, observability — into a portable .tar.gz"
  homepage "https://github.com/kmcd/xray"
  version "0.4.10"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/kmcd/xray/releases/download/v#{version}/xray_#{version}_darwin_amd64.tar.gz"
      sha256 "524e8802c0ec63c1e4e26e3e6f096fa90d3202cddd47aaa40465c91d310403c7"
    end
    on_arm do
      url "https://github.com/kmcd/xray/releases/download/v#{version}/xray_#{version}_darwin_arm64.tar.gz"
      sha256 "4124ea29061a783c4f4daaf98d3431c13fb4ef1f4f7adae2a127e5ce432b169b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kmcd/xray/releases/download/v#{version}/xray_#{version}_linux_amd64.tar.gz"
      sha256 "59ac029738bef4e80e0a5975935683ca763329b8dc006d9bb5bda876b74889be"
    end
    on_arm do
      url "https://github.com/kmcd/xray/releases/download/v#{version}/xray_#{version}_linux_arm64.tar.gz"
      sha256 "a22c763c5810f7eebd1b8d3ca41290c536b86fa454127ad93fad064c82a30d9d"
    end
  end

  livecheck do
    skip "Auto-generated on release."
  end

  def install
    bin.install "xray"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/xray version")
  end
end
