#!/bin/sh
# publish-tap.sh — render and publish brew Cask + Scoop manifest for a release.
#
# Usage:
#   scripts/publish-tap.sh [TAG]
#
# TAG defaults to the latest tag (`git describe --tags --abbrev=0`).
# Run on `main`, after `git tag vX.Y.Z && git push --tags` and after CI's
# release.yml has published the GitHub release with binaries + checksums.
#
# What it does:
#   1. Downloads checksums.txt from the GitHub release.
#   2. Renders Casks/xray.rb (brew Cask) and bucket/xray.json (Scoop manifest)
#      with the real CI-built sha256s for all five platform archives.
#   3. Pathspec-commits and pushes to main.
#
# Exits 0 on success, or 0 with a "nothing to publish" message when the
# current Cask + manifest already match the target tag.

set -eu

TAG=${1:-$(git describe --tags --abbrev=0)}
TAG=v${TAG#v}
VERSION=${TAG#v}

REPO=kmcd/xray

err() {
    printf 'publish-tap: %s\n' "$*" >&2
    exit 1
}

require() {
    command -v "$1" >/dev/null 2>&1 || err "missing required tool: $1"
}

require gh
require git
require awk

[ -z "$(git status --porcelain)" ] \
    || err "working tree not clean; commit or stash before publishing"

branch=$(git rev-parse --abbrev-ref HEAD)
[ "$branch" = "main" ] \
    || err "not on main (on $branch); switch branches before publishing"

gh release view "$TAG" --repo "$REPO" --json name >/dev/null 2>&1 \
    || err "no GitHub release for $TAG; tag may not be pushed or CI may still be running"

workdir=$(mktemp -d)
trap 'rm -rf "$workdir"' EXIT

printf 'publish-tap: downloading checksums for %s\n' "$TAG" >&2
gh release download "$TAG" --repo "$REPO" -p checksums.txt -D "$workdir" \
    || err "could not download checksums.txt from $TAG release"

sha_for() {
    awk -v f="$1" '$2==f {print $1}' "$workdir/checksums.txt"
}

SHA_DARWIN_AMD64=$(sha_for "xray_${VERSION}_darwin_amd64.tar.gz")
SHA_DARWIN_ARM64=$(sha_for "xray_${VERSION}_darwin_arm64.tar.gz")
SHA_LINUX_AMD64=$(sha_for "xray_${VERSION}_linux_amd64.tar.gz")
SHA_LINUX_ARM64=$(sha_for "xray_${VERSION}_linux_arm64.tar.gz")
SHA_WINDOWS_AMD64=$(sha_for "xray_${VERSION}_windows_amd64.zip")

[ -n "$SHA_DARWIN_AMD64" ]  || err "no checksum for xray_${VERSION}_darwin_amd64.tar.gz"
[ -n "$SHA_DARWIN_ARM64" ]  || err "no checksum for xray_${VERSION}_darwin_arm64.tar.gz"
[ -n "$SHA_LINUX_AMD64" ]   || err "no checksum for xray_${VERSION}_linux_amd64.tar.gz"
[ -n "$SHA_LINUX_ARM64" ]   || err "no checksum for xray_${VERSION}_linux_arm64.tar.gz"
[ -n "$SHA_WINDOWS_AMD64" ] || err "no checksum for xray_${VERSION}_windows_amd64.zip"

mkdir -p Casks bucket

# Cask: keep `desc:`, `homepage:`, `name:` strings in sync with the
# `homebrew_casks:` stanza in .goreleaser.yaml (single source of truth lives
# in the release config, mirrored here at render time).
cat > Casks/xray.rb <<EOF
# This file was generated by scripts/publish-tap.sh. DO NOT EDIT.
cask "xray" do
  version "${VERSION}"

  on_macos do
    on_intel do
      sha256 "${SHA_DARWIN_AMD64}"
      url "https://github.com/${REPO}/releases/download/v#{version}/xray_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "${SHA_DARWIN_ARM64}"
      url "https://github.com/${REPO}/releases/download/v#{version}/xray_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "${SHA_LINUX_AMD64}"
      url "https://github.com/${REPO}/releases/download/v#{version}/xray_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "${SHA_LINUX_ARM64}"
      url "https://github.com/${REPO}/releases/download/v#{version}/xray_#{version}_linux_arm64.tar.gz"
    end
  end

  name "xray"
  desc "Read-only extractor for engineering metrics — git, GitHub, CI, observability — into a portable .tar.gz"
  homepage "https://github.com/${REPO}"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "xray"

  # Strip macOS Gatekeeper's quarantine xattr so the cosign-signed (but not
  # Apple-notarized) binary runs without the "Apple could not verify..."
  # dialog. The binary's provenance is verified by Sigstore + SLSA L3, not
  # Apple notarization; this postflight tells macOS to skip its own check.
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{staged_path}/xray"],
                   sudo: false
  end
end
EOF

cat > bucket/xray.json <<EOF
{
    "version": "${VERSION}",
    "architecture": {
        "64bit": {
            "url": "https://github.com/${REPO}/releases/download/v${VERSION}/xray_${VERSION}_windows_amd64.zip",
            "bin": [
                "xray.exe"
            ],
            "hash": "${SHA_WINDOWS_AMD64}"
        }
    },
    "homepage": "https://github.com/${REPO}",
    "license": "Apache-2.0",
    "description": "Read-only extractor for engineering metrics"
}
EOF

if [ -z "$(git status --porcelain -- Casks/xray.rb bucket/xray.json)" ]; then
    printf 'publish-tap: Cask + manifest already match %s; nothing to commit\n' "$TAG" >&2
    exit 0
fi

# `git commit -- <paths>` requires the paths to be tracked; new files must
# be staged first so git knows about them.
git add -- Casks/xray.rb bucket/xray.json
git commit -m "release: ${TAG} brew Cask + Scoop manifest" \
    -- Casks/xray.rb bucket/xray.json

git push

printf 'publish-tap: published Cask + Scoop manifest for %s\n' "$TAG" >&2
printf 'publish-tap: release page  https://github.com/%s/releases/tag/%s\n' "$REPO" "$TAG" >&2
printf 'publish-tap: cask file     https://github.com/%s/blob/main/Casks/xray.rb\n' "$REPO" >&2
printf 'publish-tap: scoop manifest https://github.com/%s/blob/main/bucket/xray.json\n' "$REPO" >&2
