package main

import (
	"context"
	"errors"
	"fmt"
	"os"
	"sort"
	"strings"
	"text/template"

	"github.com/google/go-github/v66/github"
	"github.com/spf13/cobra"
	"golang.org/x/oauth2"
)

type initOpts struct {
	org   string
	out   string
	token string
	force bool
}

// initResult is the JSON shape emitted by `xray init --output json`.
type initResult struct {
	Kind        string `json:"kind"`
	OK          bool   `json:"ok"`
	ConfigPath  string `json:"config_path"`
	Overwritten bool   `json:"overwritten"`
}

func newInitCmd() *cobra.Command {
	var opts initOpts
	cmd := &cobra.Command{
		Use:   "init --org <github-org>",
		Short: "Generate a starter TOML config from a GitHub org",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			mode, err := ResolveMode(flagOutput, flagQuiet)
			if err != nil {
				return silentCode(err, 1)
			}
			if opts.org == "" {
				return errors.New("--org is required")
			}
			tok := opts.token
			if tok == "" {
				tok = os.Getenv("GITHUB_TOKEN")
			}
			if tok == "" {
				return errors.New("no GitHub token provided (set --token or $GITHUB_TOKEN)")
			}
			overwritten := false
			if _, statErr := os.Stat(opts.out); statErr == nil {
				if !opts.force {
					return fmt.Errorf("%s already exists (pass --force to overwrite)", opts.out)
				}
				overwritten = true
			}

			ctx := cmd.Context()
			repos, err := listOrgRepos(ctx, tok, opts.org)
			if err != nil {
				return fmt.Errorf("listing repos for %s: %w", opts.org, err)
			}
			if len(repos) == 0 {
				return fmt.Errorf("no repos found under org %q", opts.org)
			}
			sort.Strings(repos)

			body, err := renderScaffold(opts.org, repos)
			if err != nil {
				return err
			}
			// #nosec G703 -- opts.out is the user-supplied --out path; writing
			// to it is the intended behaviour of `xray init`.
			if err := os.WriteFile(opts.out, []byte(body), 0o600); err != nil {
				return fmt.Errorf("writing %s: %w", opts.out, err)
			}
			switch mode {
			case ModeQuiet:
				// success: nothing on stdout.
			case ModeJSON:
				_ = emitJSONLine(cmd.OutOrStdout(), initResult{
					Kind: "init_summary", OK: true, ConfigPath: opts.out, Overwritten: overwritten,
				})
			default:
				fmt.Fprintf(cmd.OutOrStdout(), "wrote %s (%d repos under team \"unassigned\")\n", opts.out, len(repos))
				fmt.Fprintln(cmd.OutOrStdout(), "next: edit the file to set tokens, split repos into teams, and pick a window")
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&opts.org, "org", "", "GitHub organisation to discover repos from (required)")
	cmd.Flags().StringVar(&opts.out, "out", "xray.toml", "output path for the generated config")
	cmd.Flags().StringVar(&opts.token, "token", "", "GitHub token (else $GITHUB_TOKEN)")
	cmd.Flags().BoolVar(&opts.force, "force", false, "overwrite the output file if it already exists")
	return cmd
}

// newGitHubClient builds an authenticated go-github client. It is a package
// variable so tests can swap in a client pointed at httptest.NewServer.
var newGitHubClient = func(ctx context.Context, token string) *github.Client {
	ts := oauth2.StaticTokenSource(&oauth2.Token{AccessToken: token})
	tc := oauth2.NewClient(ctx, ts)
	return github.NewClient(tc)
}

// listOrgRepos paginates the GitHub REST repos-by-org listing and returns
// owner/repo slugs in stable order.
func listOrgRepos(ctx context.Context, token, org string) ([]string, error) {
	client := newGitHubClient(ctx, token)

	var out []string
	opt := &github.RepositoryListByOrgOptions{
		ListOptions: github.ListOptions{PerPage: 100},
	}
	for {
		page, resp, err := client.Repositories.ListByOrg(ctx, org, opt)
		if err != nil {
			return nil, err
		}
		for _, r := range page {
			if r == nil || r.FullName == nil {
				continue
			}
			out = append(out, r.GetFullName())
		}
		if resp == nil || resp.NextPage == 0 {
			break
		}
		opt.Page = resp.NextPage
	}
	return out, nil
}

const scaffoldTmpl = `# generated by xray init --org {{.Org}}
# review and edit before running:
#   - set the extraction window
#   - split [teams] into real team groupings
#   - paste a token into each connector block you want to enable
#   - delete connector blocks you do not need

# TODO: set the extraction window, format: YYYY-MM-DD..YYYY-MM-DD
window = ""

# Set true to capture the content of harness/AI-tool config files
# (CLAUDE.md, .cursor/rules, etc.) in addition to metadata. Default false.
capture_harness_content = false

[teams]
unassigned = [
{{- range .Repos }}
    "{{.}}",
{{- end }}
]

[connectors.github]
token = ""

[connectors.github_actions]
# Inherits token from [connectors.github] by default; set token here to override.

[connectors.circleci]
token = ""
[connectors.circleci.projects]
# "gh/owner/repo" = "owner/repo"

[connectors.sentry]
token = ""
organization = ""
[connectors.sentry.projects]
# "sentry-project-slug" = "owner/repo"

[connectors.bugsnag]
token = ""
[connectors.bugsnag.projects]
# "bugsnag-project-slug" = "owner/repo"

[connectors.honeycomb]
token = ""
dataset = ""
`

func renderScaffold(org string, repos []string) (string, error) {
	t, err := template.New("scaffold").Parse(scaffoldTmpl)
	if err != nil {
		return "", err
	}
	var buf strings.Builder
	if err := t.Execute(&buf, struct {
		Org   string
		Repos []string
	}{Org: org, Repos: repos}); err != nil {
		return "", err
	}
	return buf.String(), nil
}
