package main

import (
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// ---------- unit tests (no network) ----------

func TestNormalizeSlug(t *testing.T) {
	cases := []struct {
		in   string
		want string
	}{
		{"dealers-site", "dealers_site"},
		{"dealers_site", "dealers_site"},
		{"Dealers Site", "dealers_site"},
		{"admin-js", "admin"},
		{"api-ruby", "api"},
		{"backend-python", "backend"},
		{"foo.bar", "foo_bar"},
		{"MyRepo", "myrepo"},
	}
	for _, c := range cases {
		if got := normalizeSlug(c.in); got != c.want {
			t.Errorf("normalizeSlug(%q) = %q, want %q", c.in, got, c.want)
		}
	}
}

func TestMatchRepo(t *testing.T) {
	repos := []string{
		"acme/dealers_site",
		"acme/admin_site",
		"acme/api",
	}
	cases := []struct {
		projectName string
		wantSlug    string
		wantConf    string
	}{
		{"dealers-site", "acme/dealers_site", "high"},
		{"dealers_site", "acme/dealers_site", "high"},
		{"Dealers Site", "acme/dealers_site", "high"},
		{"admin-site", "acme/admin_site", "high"},
		// _js suffix stripped by normalizeSlug → exact match
		{"dealers-site-js", "acme/dealers_site", "high"},
		// no match
		{"notaproject", "", ""},
	}
	for _, c := range cases {
		gotSlug, gotConf := matchRepo(c.projectName, repos)
		if gotSlug != c.wantSlug || gotConf != c.wantConf {
			t.Errorf("matchRepo(%q) = (%q, %q), want (%q, %q)",
				c.projectName, gotSlug, gotConf, c.wantSlug, c.wantConf)
		}
	}
}

func TestProbeLinkNext(t *testing.T) {
	cases := []struct {
		header string
		want   string
	}{
		{`<https://api.bugsnag.com/orgs/1/projects?page=2>; rel="next"`, "https://api.bugsnag.com/orgs/1/projects?page=2"},
		{`<https://api.bugsnag.com/orgs/1/projects?page=1>; rel="prev", <https://api.bugsnag.com/orgs/1/projects?page=3>; rel="next"`, "https://api.bugsnag.com/orgs/1/projects?page=3"},
		{`<https://api.bugsnag.com/orgs/1/projects?page=1>; rel="prev"`, ""},
		{"", ""},
	}
	for _, c := range cases {
		if got := probeLinkNext(c.header); got != c.want {
			t.Errorf("probeLinkNext(%q) = %q, want %q", c.header, got, c.want)
		}
	}
}

func TestProbeSentryNextLink(t *testing.T) {
	cases := []struct {
		header string
		want   string
	}{
		{
			`<https://sentry.io/api/0/projects/?cursor=0:25:0>; rel="next"; results="true"; cursor="0:25:0"`,
			"https://sentry.io/api/0/projects/?cursor=0:25:0",
		},
		{
			`<https://sentry.io/api/0/projects/?cursor=0:0:1>; rel="previous"; results="false", <https://sentry.io/api/0/projects/?cursor=0:25:0>; rel="next"; results="true"`,
			"https://sentry.io/api/0/projects/?cursor=0:25:0",
		},
		{
			`<https://sentry.io/api/0/projects/?cursor=0:25:0>; rel="next"; results="false"`,
			"",
		},
		{"", ""},
	}
	for _, c := range cases {
		if got := probeSentryNextLink(c.header); got != c.want {
			t.Errorf("probeSentryNextLink(%q) = %q, want %q", c.header, got, c.want)
		}
	}
}

func TestRenderProbeDraft_ContainsExpectedSections(t *testing.T) {
	r := probeResult{
		Org: "acme",
		GitHub: ghProbe{
			ActiveRepos: []string{"acme/api", "acme/web"},
		},
		CircleCI: cciProbe{
			Followed: []cciFollowed{
				{CCISlug: "gh/acme/api", RepoSlug: "acme/api"},
			},
		},
		Bugsnag: bnProbe{
			OrgName:  "Acme Inc",
			Projects: []bnProject{{ID: "abc123", Name: "api-backend"}},
			Matches:  []bnMatch{{Project: bnProject{ID: "abc123", Name: "api-backend"}, RepoSlug: "acme/api", Confidence: "high"}},
		},
		Honeycomb: hcProbe{
			Datasets:    []hcDataset{{Name: "production", Slug: "production"}},
			Attribution: []hcAttr{{Dataset: "production", RepoSlug: "acme/api", MarkerCount: 100}},
		},
		Sentry: sentryProbe{
			OrgSlug:  "acme-sentry",
			Projects: []sentryProject{{Slug: "web-app", Name: "Web App"}},
			Matches:  []sentryMatch{{Project: sentryProject{Slug: "web-app", Name: "Web App"}, RepoSlug: "acme/web", Confidence: "medium"}},
		},
	}

	body, err := renderProbeDraft(r)
	if err != nil {
		t.Fatalf("renderProbeDraft: %v", err)
	}

	checks := []string{
		"generated by xray init --from-org acme --probe",
		`"acme/api"`,
		`"acme/web"`,
		`"gh/acme/api" = "acme/api"`,        // CircleCI mapping
		`"abc123" = "acme/api"`,              // Bugsnag mapping
		`dataset = "production"`,             // Honeycomb recommended
		`"web-app" = "acme/web"`,             // Sentry mapping
		`organization = "acme-sentry"`,
	}
	for _, want := range checks {
		if !strings.Contains(body, want) {
			t.Errorf("renderProbeDraft missing %q\nfull output:\n%s", want, body)
		}
	}
}

func TestRenderProbeDraft_SkippedConnectors(t *testing.T) {
	r := probeResult{
		Org:       "acme",
		GitHub:    ghProbe{ActiveRepos: []string{"acme/api"}},
		CircleCI:  cciProbe{Skipped: true, SkipReason: "CIRCLECI_TOKEN not set"},
		Bugsnag:   bnProbe{Skipped: true, SkipReason: "BUGSNAG_AUTH_TOKEN not set"},
		Honeycomb: hcProbe{Skipped: true, SkipReason: "HONEYCOMB_API_KEY not set"},
		Sentry:    sentryProbe{Skipped: true, SkipReason: "SENTRY_AUTH_TOKEN not set"},
	}

	body, err := renderProbeDraft(r)
	if err != nil {
		t.Fatalf("renderProbeDraft: %v", err)
	}
	// All connector blocks present with placeholder comments.
	for _, want := range []string{
		"[connectors.circleci]",
		"[connectors.bugsnag]",
		"[connectors.honeycomb]",
		"[connectors.sentry]",
		`dataset = ""`,
	} {
		if !strings.Contains(body, want) {
			t.Errorf("renderProbeDraft missing %q", want)
		}
	}
}

// ---------- connector probe tests with fake HTTP servers ----------

func TestProbeCCI_MapsFollowedProjects(t *testing.T) {
	mux := http.NewServeMux()
	mux.HandleFunc("/projects", func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode([]map[string]any{
			{"vcs_type": "github", "username": "acme", "reponame": "api"},
			{"vcs_type": "github", "username": "acme", "reponame": "web"},
			{"vcs_type": "github", "username": "other-org", "reponame": "stuff"},   // wrong org, filtered
			{"vcs_type": "bitbucket", "username": "acme", "reponame": "payments"},  // wrong vcs, filtered
		})
	})
	srv := httptest.NewServer(mux)
	defer srv.Close()

	orig := probeCCIBaseURL
	probeCCIBaseURL = srv.URL
	defer func() { probeCCIBaseURL = orig }()

	result := probeCCI(t.Context(), srv.Client(), "tok", "acme")
	if result.Skipped {
		t.Fatalf("unexpected skip: %s", result.SkipReason)
	}
	if len(result.Followed) != 2 {
		t.Fatalf("len(Followed) = %d, want 2", len(result.Followed))
	}
	if result.Followed[0].CCISlug != "gh/acme/api" || result.Followed[0].RepoSlug != "acme/api" {
		t.Errorf("Followed[0] = %+v", result.Followed[0])
	}
}

func TestProbeCCI_SkipsOnHTTPError(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		http.Error(w, "unauthorized", http.StatusUnauthorized)
	}))
	defer srv.Close()

	orig := probeCCIBaseURL
	probeCCIBaseURL = srv.URL
	defer func() { probeCCIBaseURL = orig }()

	result := probeCCI(t.Context(), srv.Client(), "bad-tok", "acme")
	if !result.Skipped {
		t.Error("expected Skipped=true on 401")
	}
}

func TestProbeBugsnag_MatchesProjects(t *testing.T) {
	mux := http.NewServeMux()
	mux.HandleFunc("/organizations", func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode([]map[string]any{
			{"id": "org1", "name": "Acme Inc", "slug": "acme"},
		})
	})
	mux.HandleFunc("/organizations/org1/projects", func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode([]map[string]any{
			{"id": "pid1", "name": "dealers-site", "slug": "dealers-site"},
			{"id": "pid2", "name": "admin-panel", "slug": "admin-panel"},
		})
	})
	srv := httptest.NewServer(mux)
	defer srv.Close()

	orig := probeBugsnagBaseURL
	probeBugsnagBaseURL = srv.URL
	defer func() { probeBugsnagBaseURL = orig }()

	repos := []string{"acme/dealers_site", "acme/web"}
	result := probeBugsnag(t.Context(), srv.Client(), "tok", repos)
	if result.Skipped {
		t.Fatalf("unexpected skip: %s", result.SkipReason)
	}
	if result.OrgName != "Acme Inc" {
		t.Errorf("OrgName = %q, want %q", result.OrgName, "Acme Inc")
	}
	if len(result.Projects) != 2 {
		t.Fatalf("len(Projects) = %d, want 2", len(result.Projects))
	}
	if len(result.Matches) != 1 || result.Matches[0].Project.ID != "pid1" {
		t.Errorf("Matches = %+v, want single high-confidence dealers_site match", result.Matches)
	}
	if len(result.Unmatched) != 1 || result.Unmatched[0].ID != "pid2" {
		t.Errorf("Unmatched = %+v, want single admin-panel entry", result.Unmatched)
	}
}

func TestProbeHoneycomb_AttributesMarkers(t *testing.T) {
	mux := http.NewServeMux()
	mux.HandleFunc("/datasets", func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode([]map[string]any{
			{"name": "production", "slug": "production"},
			{"name": "staging", "slug": "staging"},
		})
	})
	mux.HandleFunc("/markers/production", func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode([]map[string]any{
			{"url": "https://github.com/acme/api/commit/abc"},
			{"url": "https://github.com/acme/api/commit/def"},
			{"url": "https://github.com/other/repo/commit/xyz"}, // different org
		})
	})
	mux.HandleFunc("/markers/staging", func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode([]map[string]any{}) // no markers
	})
	srv := httptest.NewServer(mux)
	defer srv.Close()

	orig := probeHoneycombBaseURL
	probeHoneycombBaseURL = srv.URL
	defer func() { probeHoneycombBaseURL = orig }()

	repos := []string{"acme/api", "acme/web"} // web has no markers
	result := probeHoneycomb(t.Context(), srv.Client(), "tok", "acme", repos)
	if result.Skipped {
		t.Fatalf("unexpected skip: %s", result.SkipReason)
	}
	if len(result.Datasets) != 2 {
		t.Errorf("len(Datasets) = %d, want 2", len(result.Datasets))
	}
	if len(result.Attribution) != 1 {
		t.Fatalf("len(Attribution) = %d, want 1", len(result.Attribution))
	}
	if result.Attribution[0].RepoSlug != "acme/api" || result.Attribution[0].MarkerCount != 2 {
		t.Errorf("Attribution[0] = %+v", result.Attribution[0])
	}
	if len(result.NoMarkers) != 1 || result.NoMarkers[0] != "acme/web" {
		t.Errorf("NoMarkers = %v, want [acme/web]", result.NoMarkers)
	}
}

func TestProbeSentry_MatchesAndPaginates(t *testing.T) {
	page2URL := ""
	mux := http.NewServeMux()
	mux.HandleFunc("/projects/", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		if r.URL.RawQuery == "cursor=1" {
			// second page — no next link
			_ = json.NewEncoder(w).Encode([]map[string]any{
				{"slug": "backend", "name": "Backend", "organization": map[string]any{"slug": "acme-sentry"}},
			})
			return
		}
		// first page — includes next link pointing at cursor=1
		page2URL = "http://" + r.Host + "/projects/?cursor=1"
		w.Header().Set("Link", `<`+page2URL+`>; rel="next"; results="true"`)
		_ = json.NewEncoder(w).Encode([]map[string]any{
			{"slug": "frontend", "name": "Frontend", "organization": map[string]any{"slug": "acme-sentry"}},
		})
	})
	srv := httptest.NewServer(mux)
	defer srv.Close()

	orig := probeSentryBaseURL
	probeSentryBaseURL = srv.URL
	defer func() { probeSentryBaseURL = orig }()

	repos := []string{"acme/frontend", "acme/api"}
	result := probeSentry(t.Context(), srv.Client(), "tok", repos)
	if result.Skipped {
		t.Fatalf("unexpected skip: %s", result.SkipReason)
	}
	if len(result.Projects) != 2 {
		t.Fatalf("len(Projects) = %d, want 2 (pagination should collect both pages)", len(result.Projects))
	}
	if result.OrgSlug != "acme-sentry" {
		t.Errorf("OrgSlug = %q, want %q", result.OrgSlug, "acme-sentry")
	}
	// "frontend" matches "acme/frontend" — high confidence
	if len(result.Matches) != 1 || result.Matches[0].Project.Slug != "frontend" {
		t.Errorf("Matches = %+v", result.Matches)
	}
}

// ---------- integration: xray init --probe command ----------

func TestInitProbe_WritesScaffold(t *testing.T) {
	// Set up a fake GitHub server (reused withFakeGitHub from init_test.go).
	payload := `[
		{"name": "api", "full_name": "acme/api", "archived": false, "pushed_at": "2099-01-01T00:00:00Z"},
		{"name": "web", "full_name": "acme/web", "archived": false, "pushed_at": "2099-01-01T00:00:00Z"}
	]`
	withFakeGitHub(t, payload)

	// Fake CircleCI server.
	cciSrv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode([]map[string]any{
			{"vcs_type": "github", "username": "acme", "reponame": "api"},
		})
	}))
	defer cciSrv.Close()
	origCCI := probeCCIBaseURL
	probeCCIBaseURL = cciSrv.URL
	defer func() { probeCCIBaseURL = origCCI }()

	// Point other connectors at a stub that returns 401 (they'll be skipped).
	stub401 := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		http.Error(w, "unauthorized", http.StatusUnauthorized)
	}))
	defer stub401.Close()
	origBn := probeBugsnagBaseURL
	origHC := probeHoneycombBaseURL
	origSe := probeSentryBaseURL
	probeBugsnagBaseURL = stub401.URL
	probeHoneycombBaseURL = stub401.URL
	probeSentryBaseURL = stub401.URL
	defer func() {
		probeBugsnagBaseURL = origBn
		probeHoneycombBaseURL = origHC
		probeSentryBaseURL = origSe
	}()

	outPath := filepath.Join(t.TempDir(), "xray.toml.draft")
	t.Setenv("CIRCLECI_TOKEN", "tok")
	t.Setenv("BUGSNAG_AUTH_TOKEN", "")
	t.Setenv("HONEYCOMB_API_KEY", "")
	t.Setenv("HC_API_KEY", "")
	t.Setenv("SENTRY_AUTH_TOKEN", "")

	root, stdout, stderr := newTestRoot(t)
	root.SetArgs([]string{"init", "--from-org", "acme", "--token", "ghtoken", "--probe", "--out", outPath})
	if err := root.Execute(); err != nil {
		t.Fatalf("init --probe err: %v (stderr=%q)", err, stderr.String())
	}

	body, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatalf("read draft: %v", err)
	}
	bs := string(body)

	if !strings.Contains(bs, `"acme/api"`) || !strings.Contains(bs, `"acme/web"`) {
		t.Errorf("draft missing expected repos:\n%s", bs)
	}
	if !strings.Contains(bs, `"gh/acme/api" = "acme/api"`) {
		t.Errorf("draft missing CircleCI mapping:\n%s", bs)
	}
	if !strings.Contains(stdout.String(), "Wrote") {
		t.Errorf("stdout missing 'Wrote' line: %q", stdout.String())
	}
}

func TestInitProbe_RequiresOrg(t *testing.T) {
	root, _, _ := newTestRoot(t)
	root.SetArgs([]string{"init", "--probe", "--token", "tok"})
	if err := root.Execute(); err == nil {
		t.Fatal("expected error when --from-org is missing")
	}
}

func TestInitProbe_RefusesOverwrite(t *testing.T) {
	payload := `[{"name": "api", "full_name": "acme/api", "archived": false}]`
	withFakeGitHub(t, payload)

	outPath := filepath.Join(t.TempDir(), "xray.toml.draft")
	if err := os.WriteFile(outPath, []byte("existing"), 0o600); err != nil {
		t.Fatal(err)
	}

	// --probe without --force should refuse to overwrite.
	cciSrv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte("[]"))
	}))
	defer cciSrv.Close()
	orig := probeCCIBaseURL
	probeCCIBaseURL = cciSrv.URL
	defer func() { probeCCIBaseURL = orig }()

	stub401 := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		http.Error(w, "unauthorized", http.StatusUnauthorized)
	}))
	defer stub401.Close()
	for _, p := range []*string{&probeBugsnagBaseURL, &probeHoneycombBaseURL, &probeSentryBaseURL} {
		orig := *p
		*p = stub401.URL
		defer func(pp *string, o string) { *pp = o }(p, orig)
	}

	t.Setenv("CIRCLECI_TOKEN", "tok")
	t.Setenv("BUGSNAG_AUTH_TOKEN", "")
	t.Setenv("HONEYCOMB_API_KEY", "")
	t.Setenv("HC_API_KEY", "")
	t.Setenv("SENTRY_AUTH_TOKEN", "")

	root, _, _ := newTestRoot(t)
	root.SetArgs([]string{"init", "--from-org", "acme", "--token", "tok", "--probe", "--out", outPath})
	err := root.Execute()
	if err == nil {
		t.Fatal("expected error refusing to overwrite")
	}
	if !strings.Contains(err.Error(), "already exists") {
		t.Errorf("err = %v, want 'already exists'", err)
	}
	got, _ := os.ReadFile(outPath)
	if string(got) != "existing" {
		t.Error("file was modified without --force")
	}
}
